#ifndef ERRORCODE_H
#define ERRORCODE_H

// #define SUCCESS 0
#define ERROR_INVALID_ARGUMENT 1
#define ERROR_OPEN_FILE 2
#define ERROR_PARSE_NETLIST 3
#define ERROR_UNKOWN_LINE_TYPE 4

#endif // ERRORCODE_H
