#ifndef LINETYPE_H
#define LINETYPE_H

#define LINE_TYPE_COMMENT 0
#define COMPONENT_RESISTOR 1
#define COMPONENT_CAPACITOR 2
#define COMPONENT_INDUCTOR 3
#define COMPONENT_VCVS 4
#define COMPONENT_CCCS 5
#define COMPONENT_VCCS 6
#define COMPONENT_CCVS 7
#define COMPONENT_VOLTAGE_SOURCE 8
#define COMPONENT_CURRENT_SOURCE 9

#define ANALYSIS_OP 11
#define ANALYSIS_DC 12
#define ANALYSIS_AC 13
#define ANALYSIS_TRAN 14
#define ANALYSIS_PRINT 15
#define ANALYSIS_PLOT 16
#define ANALYSIS_END 17
#define ANALYSIS_OPTIONS 18

#endif // LINETYPE_H
