#ifndef TOKENTYPE_H
#define TOKENTYPE_H

#define TOKEN_ANALYSIS_OP 1
#define TOKEN_ANALYSIS_DC 2
#define TOKEN_ANALYSIS_AC 3
#define TOKEN_ANALYSIS_TRAN 4

#define TOKEN_DEC 1
#define TOKEN_OCT 2
#define TOKEN_LIN 3

#define TOKEN_VAR_VOLTAGE_REAL 1
#define TOKEN_VAR_VOLTAGE_IMAG 2
#define TOKEN_VAR_VOLTAGE_MAG 3
#define TOKEN_VAR_VOLTAGE_PHASE 4
#define TOKEN_VAR_VOLTAGE_DB 5
#define TOKEN_VAR_CURRENT_REAL 6
#define TOKEN_VAR_CURRENT_IMAG 7
#define TOKEN_VAR_CURRENT_MAG 8
#define TOKEN_VAR_CURRENT_PHASE 9
#define TOKEN_VAR_CURRENT_DB 10

#define TOKEN_OPTION_NODE 1
#define TOKEN_OPTION_LIST 2

#endif // TOKENTYPE_H
